name: "TODO"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@mv4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v5"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
